# Change these first
owner: Neogoma # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Neogoma Website
    url: https://www.neogoma.com
  - name: Stardust Dashboard
    url: https://stardust.neogoma.com/current_version
  - name: Stardust API
    url: https://lothal.neogoma.com/api/current_version
  - name: Stardust relocation service
    url: https://dagobah.neogoma.com/api/current_version
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.neogoma.com
  #baseUrl: /uptime
  logoUrl: https://stardust.neogoma.com/img/logo.png
  name: Neogoma's status page
  introTitle: "Status of all public Neogoma's services"
  introMessage: This is the actual status of all the neogoma services
  navbar:
    - title: Status
      href: /
    - title: Stardust
      href: https://stardust.neogoma.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
